### PR TITLE
added two dutch translation and the time they took

### PR DESCRIPTION
**Pull request by Arriu**

### CODE REVIEW

**Comment by artikozel** [comment]
Merging. Excellent work! Thanks and keep 'em coming :)

**Comment by xaur** [comment]
@artikozel @Arriu this was merged into `testbranch` because it was opened against `testbranch`. It's not in master.

**Comment by xaur** [comment]
Try `git chery-pick` the comment on master.

**Comment by artikozel** [comment]
@xaur, this was by design. I'll merge it into master shortly.

**Pull request merged**
